const Icons: { [key: number]: unknown } = {
  0: "wi-day-sunny",
  1: "wi-day-sunny-overcast",
  2: "wi-day-sunny-overcast",
  3: "wi-day-sunny-overcast",
  45: "wi-day-fog",
  48: "wi-day-fog",
  51: "wi-day-hail",
  53: "wi-day-hail",
  55: "wi-day-hail",
  56: "wi-day-snow-wind",
  57: "wi-day-snow-wind",
  61: "wi-day-rain",
  63: "wi-day-rain",
  65: "wi-day-rain",
  66: "wi-day-snow-wind",
  67: "wi-day-snow-wind",
  71: "wi-day-snow",
  73: "wi-day-snow",
  75: "wi-day-snow",
  77: "wi-day-rain-mix",
  80: "wi-day-showers",
  81: "wi-day-showers",
  82: "wi-day-showers",
  85: "wi-day-rain-mix",
  86: "wi-day-rain-mix",
  95: "wi-day-storm-showers",
  96: "wi-day-thunderstorm ",
  99: "wi-day-thunderstorm ",
};

export default Icons;
