import Head from "next/head";
import { Card, Search, Toggle } from "../components";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-full">
        <div className="flex justify-end p-4 md:py-12 md:px-32">
          <Toggle />
        </div>
        <div className="flex justify-center">
          <div className="min-w-[784px]">
            <Search />
          </div>
        </div>
        <div>
          <Card />
        </div>
      </main>
    </>
  );
}
